remote_theme: pages-themes/cayman@v0.2.0
title: Thilini's Blog
description: [A programmer at heart. Analyzing stuff 24/7]
#show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
