theme: jekyll-theme-cayman
#remote_theme: pages-themes/cayman@v0.2.0

#show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]

# Name of your site
name: Thilini's Blog

# Name of website (site.title)
title: Thilini's Blog

# Short description of your site
#description: [A programmer at heart. Analyzing stuff 24/7]
description: A programmer at heart. Analyzing stuff 24/7

# url is the full website URL
# baseurl is the website's URL without the hostname
url: https://ThiliniSiriwardena.github.io
#baseurl: "/projectname"

github:
  is_project_page: false

github_profile:
#  url: https://github.com/odan

# Disqus comments
comments: true

# List of links in the navigation bar
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://example.com/beautiful-jekyll/"
    - Learn markdown: "http://www.example.com/"
    - GitHub Pages: "https://pages.example.com/"
  Author's home: "http://example.com"

author:
  name: Thilini Siriwardena
